import { Gig } from '@/lib/types';

export const MOCK_GIGS: Gig[] = [
  {
    id: 'mock-1',
    church_id: 'mock-church-1',
    title: 'Sunday Morning Worship Guitarist',
    description: 'Looking for an experienced guitarist to lead worship this Sunday. We play a mix of Hillsong, Elevation, and Bethel.',
    instruments_needed: ['guitar'],
    date: '2026-03-01',
    time: '9:00 AM',
    pay_offered: 150,
    status: 'open',
    created_at: '2026-02-20T10:00:00Z',
    church: {
      id: 'mock-church-1',
      role: 'church',
      display_name: 'Grace Community Church',
      bio: 'A vibrant community of believers in downtown Austin.',
      avatar_url: null,
      location_city: 'Austin',
      location_state: 'TX',
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'mock-2',
    church_id: 'mock-church-2',
    title: 'Easter Service — Full Band Needed',
    description: 'Our Easter celebration needs a full band! Drums, keys, bass, and vocals. Two rehearsals included.',
    instruments_needed: ['drums', 'keys', 'bass', 'vocals'],
    date: '2026-04-05',
    time: '8:30 AM',
    pay_offered: 300,
    status: 'open',
    created_at: '2026-02-19T14:00:00Z',
    church: {
      id: 'mock-church-2',
      role: 'church',
      display_name: 'New Life Fellowship',
      bio: 'Contemporary worship church with a heart for the community.',
      avatar_url: null,
      location_city: 'Dallas',
      location_state: 'TX',
      created_at: '2026-01-15T00:00:00Z',
    },
  },
  {
    id: 'mock-3',
    church_id: 'mock-church-3',
    title: 'Wednesday Night Keys Player',
    description: 'Casual midweek service. Laid-back atmosphere, mostly hymns with a modern twist. Great for someone looking for regular weekly work.',
    instruments_needed: ['keys'],
    date: '2026-02-26',
    time: '7:00 PM',
    pay_offered: 100,
    status: 'open',
    created_at: '2026-02-18T09:00:00Z',
    church: {
      id: 'mock-church-3',
      role: 'church',
      display_name: 'Cornerstone Baptist',
      bio: 'Traditional worship with a welcoming spirit.',
      avatar_url: null,
      location_city: 'Houston',
      location_state: 'TX',
      created_at: '2026-01-10T00:00:00Z',
    },
  },
  {
    id: 'mock-4',
    church_id: 'mock-church-4',
    title: 'Audio Tech for Youth Conference',
    description: 'Three-day youth conference needs a skilled audio tech. Must be comfortable with in-ear monitors and digital mixing boards.',
    instruments_needed: ['audio_tech'],
    date: '2026-03-15',
    time: '5:00 PM',
    pay_offered: 500,
    status: 'open',
    created_at: '2026-02-17T11:00:00Z',
    church: {
      id: 'mock-church-4',
      role: 'church',
      display_name: 'Harvest Point Church',
      bio: 'Multi-campus church reaching the next generation.',
      avatar_url: null,
      location_city: 'San Antonio',
      location_state: 'TX',
      created_at: '2026-02-01T00:00:00Z',
    },
  },
  {
    id: 'mock-5',
    church_id: 'mock-church-5',
    title: 'Vocalist for Gospel Choir Sunday',
    description: 'Special gospel choir Sunday! Looking for strong vocalists who can harmonize. Rehearsal Saturday at 4 PM.',
    instruments_needed: ['vocals'],
    date: '2026-03-08',
    time: '10:00 AM',
    pay_offered: 125,
    status: 'open',
    created_at: '2026-02-16T08:00:00Z',
    church: {
      id: 'mock-church-5',
      role: 'church',
      display_name: 'Faith Tabernacle',
      bio: 'Gospel-rooted worship in the heart of the city.',
      avatar_url: null,
      location_city: 'Atlanta',
      location_state: 'GA',
      created_at: '2026-01-20T00:00:00Z',
    },
  },
  {
    id: 'mock-6',
    church_id: 'mock-church-1',
    title: 'Bass Player — Ongoing Sundays',
    description: 'Looking for a committed bass player to join our rotation. Play 2-3 Sundays per month. Modern worship style.',
    instruments_needed: ['bass'],
    date: '2026-03-02',
    time: '9:00 AM',
    pay_offered: 175,
    status: 'open',
    created_at: '2026-02-15T16:00:00Z',
    church: {
      id: 'mock-church-1',
      role: 'church',
      display_name: 'Grace Community Church',
      bio: 'A vibrant community of believers in downtown Austin.',
      avatar_url: null,
      location_city: 'Austin',
      location_state: 'TX',
      created_at: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'mock-7',
    church_id: 'mock-church-6',
    title: 'Summer Worship Night — Full Production',
    description: 'Massive outdoor worship event for 2,000+ people. Full band, pro audio, and lighting crew needed. Three rehearsals. Catering provided.',
    instruments_needed: ['guitar', 'bass', 'drums', 'keys', 'vocals', 'audio_tech'],
    date: '2026-06-20',
    time: '6:00 PM',
    pay_offered: 750,
    status: 'open',
    created_at: '2026-02-21T12:00:00Z',
    church: {
      id: 'mock-church-6',
      role: 'church',
      display_name: 'Elevation City Church',
      bio: 'A megachurch experience bringing worship to the city.',
      avatar_url: null,
      location_city: 'Nashville',
      location_state: 'TN',
      created_at: '2026-01-05T00:00:00Z',
    },
  },
  {
    id: 'mock-8',
    church_id: 'mock-church-7',
    title: 'Christmas Concert Drummer',
    description: 'Annual Christmas concert with full orchestra backing. Looking for a versatile drummer comfortable with dynamics and brushes.',
    instruments_needed: ['drums'],
    date: '2026-12-20',
    time: '7:00 PM',
    pay_offered: 400,
    status: 'open',
    created_at: '2026-02-14T10:00:00Z',
    church: {
      id: 'mock-church-7',
      role: 'church',
      display_name: 'The Gathering Place',
      bio: 'Where creativity meets worship.',
      avatar_url: null,
      location_city: 'Nashville',
      location_state: 'TN',
      created_at: '2026-01-25T00:00:00Z',
    },
  },
];

// Threshold for "trending" — gigs paying above this are considered high-pay events
export const TRENDING_PAY_THRESHOLD = 250;
